'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.Globalization
Imports System.Resources
Imports System.Runtime.CompilerServices

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     DebuggerNonUserCode(),  _
     CompilerGenerated(),  _
     HideModuleName()>  _
    Friend Module Resources
        
        Private resourceMan As ResourceManager
        
        Private resourceCulture As CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <EditorBrowsable(EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As ResourceManager
            Get
                If ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As ResourceManager = New ResourceManager("Pronama.NamaTyping.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <EditorBrowsable(EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;SubstitutionList xmlns=&quot;http://posite-c.jp/niconamacommentviewer/substitutionlist/&quot; blacklist:updated=&quot;2017-03-19T03:02:00.000Z&quot; xmlns:blacklist=&quot;https://greasyfork.org/scripts/11567&quot;&gt;
        '''	&lt;subst_client is_regex=&quot;True&quot; status=&quot;True&quot; blacklist:type=&quot;url&quot;&gt;
        '''		&lt;old&gt;(?:ftp|http|https)://[-0-9A-Za-z!#$&amp;amp;&apos;()*+,./:;=?@_~\[\]%]*?0[0-9-]{8}(?=[0-9])&lt;/old&gt;
        '''		&lt;new&gt;$0%3&lt;/new&gt;
        '''	&lt;/subst_client&gt;
        '''	&lt;subst_client is_regex=&quot;True&quot; status=&quot;True&quot; blacklist:type=&quot;url&quot;&gt;
        '''		&lt;old&gt;((?:ftp| [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property SubstList() As String
            Get
                Return ResourceManager.GetString("SubstList", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
