'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.ComponentModel.Design
Imports System.Configuration
Imports System.Runtime.CompilerServices


<CompilerGenerated(),  _
 GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0"),  _
 EditorBrowsable(EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings 自動保存機能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    '''<summary>
    '''設定が保存されたときのアセンブリバージョン。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("設定が保存されたときのアセンブリバージョン。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue(""),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property Version() As String
        Get
            Return CType(Me("Version"),String)
        End Get
        Set
            Me("Version") = value
        End Set
    End Property
    
    '''<summary>
    '''最前面に表示。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("最前面に表示。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("False"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property Topmost() As Boolean
        Get
            Return CType(Me("Topmost"),Boolean)
        End Get
        Set
            Me("Topmost") = value
        End Set
    End Property
    
    '''<summary>
    '''ユーザー名の表示。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("ユーザー名の表示。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("False"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property ShowNameEntryMessages() As Boolean
        Get
            Return CType(Me("ShowNameEntryMessages"),Boolean)
        End Get
        Set
            Me("ShowNameEntryMessages") = value
        End Set
    End Property
    
    '''<summary>
    '''採点メッセージの表示。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("採点メッセージの表示。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("False"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property ShowPointMessages() As Boolean
        Get
            Return CType(Me("ShowPointMessages"),Boolean)
        End Get
        Set
            Me("ShowPointMessages") = value
        End Set
    End Property
    
    '''<summary>
    '''コメントの表示。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("コメントの表示。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("True"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property ShowFilteredMessages() As Boolean
        Get
            Return CType(Me("ShowFilteredMessages"),Boolean)
        End Get
        Set
            Me("ShowFilteredMessages") = value
        End Set
    End Property
    
    '''<summary>
    '''表示するコメントの接頭辞。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("表示するコメントの接頭辞。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("■"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property DisplayCommentPattern() As String
        Get
            Return CType(Me("DisplayCommentPattern"),String)
        End Get
        Set
            Me("DisplayCommentPattern") = value
        End Set
    End Property
    
    '''<summary>
    '''色付きユーザーID (コンマ区切り)。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("色付きユーザーID (コンマ区切り)。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue(""),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property HighlightUsers() As String
        Get
            Return CType(Me("HighlightUsers"),String)
        End Get
        Set
            Me("HighlightUsers") = value
        End Set
    End Property
    
    '''<summary>
    '''ログのフォントサイズ (10〜34)。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("ログのフォントサイズ (10〜34)。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("16"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property MessageFontSize() As Double
        Get
            Return CType(Me("MessageFontSize"),Double)
        End Get
        Set
            Me("MessageFontSize") = value
        End Set
    End Property
    
    '''<summary>
    '''歌詞のフォントサイズ (10〜34)。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("歌詞のフォントサイズ (10〜34)。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("20"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property LyricFontSize() As Double
        Get
            Return CType(Me("LyricFontSize"),Double)
        End Get
        Set
            Me("LyricFontSize") = value
        End Set
    End Property
    
    '''<summary>
    '''ランキングのフォントサイズ (10〜34)。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("ランキングのフォントサイズ (10〜34)。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("20"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property RankingFontSize() As Double
        Get
            Return CType(Me("RankingFontSize"),Double)
        End Get
        Set
            Me("RankingFontSize") = value
        End Set
    End Property
    
    '''<summary>
    '''歌詞・ランキング背景の不透明度。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("歌詞・ランキング背景の不透明度。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("0.6"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property BottomGridOpacity() As Double
        Get
            Return CType(Me("BottomGridOpacity"),Double)
        End Get
        Set
            Me("BottomGridOpacity") = value
        End Set
    End Property
    
    '''<summary>
    '''表示する歌詞の行数 (1〜10)。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("表示する歌詞の行数 (1〜10)。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("3"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property RecentLyricLineCount() As Integer
        Get
            Return CType(Me("RecentLyricLineCount"),Integer)
        End Get
        Set
            Me("RecentLyricLineCount") = value
        End Set
    End Property
    
    '''<summary>
    '''音量。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("音量。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("0.5"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property Volume() As Double
        Get
            Return CType(Me("Volume"),Double)
        End Get
        Set
            Me("Volume") = value
        End Set
    End Property
    
    '''<summary>
    '''ウィンドウサイズなどのパターン (0〜3)。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("ウィンドウサイズなどのパターン (0〜3)。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("2"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property WindowSizePattern() As Integer
        Get
            Return CType(Me("WindowSizePattern"),Integer)
        End Get
        Set
            Me("WindowSizePattern") = value
        End Set
    End Property
    
    '''<summary>
    '''運営NGワードについて、歌詞の一致部分を強調する。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("運営NGワードについて、歌詞の一致部分を強調する。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("True"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property BlacklistCharactersHighlight() As Boolean
        Get
            Return CType(Me("BlacklistCharactersHighlight"),Boolean)
        End Get
        Set
            Me("BlacklistCharactersHighlight") = value
        End Set
    End Property
    
    '''<summary>
    '''運営NGワードについて、歌詞の一致部分に記号を挿入する。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("運営NGワードについて、歌詞の一致部分に記号を挿入する。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("True"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property SplitBlacklistCharacters() As Boolean
        Get
            Return CType(Me("SplitBlacklistCharacters"),Boolean)
        End Get
        Set
            Me("SplitBlacklistCharacters") = value
        End Set
    End Property
    
    '''<summary>
    '''すべての部屋からコメントを取得する。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("すべての部屋からコメントを取得する。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("False"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property ConnectAllCommentServers() As Boolean
        Get
            Return CType(Me("ConnectAllCommentServers"),Boolean)
        End Get
        Set
            Me("ConnectAllCommentServers") = value
        End Set
    End Property
    
    '''<summary>
    '''経過時間と総時間を、歌詞表示領域の右上にも表示する
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("経過時間と総時間を、歌詞表示領域の右上にも表示する"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("True"),  _
     SettingsManageability(SettingsManageability.Roaming)>  _
    Public Property ShowTimeOnLyricsGrid() As Boolean
        Get
            Return CType(Me("ShowTimeOnLyricsGrid"),Boolean)
        End Get
        Set
            Me("ShowTimeOnLyricsGrid") = value
        End Set
    End Property
    
    '''<summary>
    '''ウィンドウの横位置のキャッシュ。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("ウィンドウの横位置のキャッシュ。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("NaN")>  _
    Public Property WindowLeft() As Double
        Get
            Return CType(Me("WindowLeft"),Double)
        End Get
        Set
            Me("WindowLeft") = value
        End Set
    End Property
    
    '''<summary>
    '''ウィンドウの縦位置のキャッシュ。
    '''</summary>
    <UserScopedSetting(),  _
     SettingsDescription("ウィンドウの縦位置のキャッシュ。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("NaN")>  _
    Public Property WindowTop() As Double
        Get
            Return CType(Me("WindowTop"),Double)
        End Get
        Set
            Me("WindowTop") = value
        End Set
    End Property
    
    '''<summary>
    '''運営NGワードを分断する文字。
    '''</summary>
    <ApplicationScopedSetting(),  _
     SettingsDescription("運営NGワードを分断する文字。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("/")>  _
    Public ReadOnly Property BlacklistCharactersSeparator() As String
        Get
            Return CType(Me("BlacklistCharactersSeparator"),String)
        End Get
    End Property
    
    '''<summary>
    '''NGワード置換ファイルを手動でダウンロードするURL。
    '''</summary>
    <ApplicationScopedSetting(),  _
     SettingsDescription("NGワード置換ファイルを手動でダウンロードするURL。"),  _
     DebuggerNonUserCode(),  _
     DefaultSettingValue("https://id.pokemori.jp/niconico-live-ncv")>  _
    Public ReadOnly Property SubstitutionListDownloadURL() As String
        Get
            Return CType(Me("SubstitutionListDownloadURL"),String)
        End Get
    End Property
End Class

Namespace My
    
    <HideModuleName(),  _
     DebuggerNonUserCode(),  _
     CompilerGenerated()>  _
    Friend Module MySettingsProperty
        
        <HelpKeyword("My.Settings")>  _
        Friend ReadOnly Property Settings() As MySettings
            Get
                Return MySettings.Default
            End Get
        End Property
    End Module
End Namespace
